public class car {
    public  decimal subtractMethod(decimal x,decimal y){
        decimal subtract=x-y;
        return subtract;
    }
    public static integer multiplicationMethod(integer x,integer y){
        integer mul=x*y;
        return mul;
        
    }
    public static string concenitedMethod(string firstName,string lastName){
      return firstName+' '+lastName;
        
        
    }
    
}